SELECT      A.TABLESPACE_NAME,
            A.TABLE_NAME,
            A.INDEX_NAME,
            COUNT(B.COLUMN_POSITION) TOT_COLUMN_POSITION,
            SUM( DECODE( C.DATA_TYPE, 'NUMBER', DATA_PRECISION, DATA_LENGTH ) ) TAM_DADOS,
            MAX( A.NUM_ROWS) AS MAX_NUM_ROWS,
            MAX( D.BLOCKS) AS MAX_BLOCKS       
FROM        DBA_INDEXES A
INNER JOIN  DBA_IND_COLUMNS B
    ON      A.TABLE_OWNER = B.TABLE_OWNER
    AND     A.TABLE_NAME  = B.TABLE_NAME
    AND     A.INDEX_NAME  = B.INDEX_NAME
INNER JOIN  DBA_TAB_COLUMNS C
    ON      B.TABLE_OWNER = C.OWNER
    AND     B.TABLE_NAME  = C.TABLE_NAME
    AND     B.COLUMN_NAME = C.COLUMN_NAME
INNER JOIN  DBA_SEGMENTS D
    ON      A.OWNER = D.OWNER
    AND     A.INDEX_NAME  = D.SEGMENT_NAME
GROUP BY    A.TABLESPACE_NAME, A.TABLE_NAME, A.INDEX_NAME
ORDER BY    A.TABLESPACE_NAME, A.TABLE_NAME, A.INDEX_NAME;