-- Se for necessario apague o indice invalido
DROP INDEX  &SCHEMA_NAME.&INDEX_NAME FORCE;
/

DECLARE
  v_novo_tbs varchar2(100):='&NOVO_TBS';
BEGIN
      ctx_ddl.create_preference('MY_TEXT_STORE', 'BASIC_STORAGE');
      CTX_DDL.SET_ATTRIBUTE('MY_TEXT_STORE', 'I_TABLE_CLAUSE','TABLESPACE ' || v_novo_tbs);
      CTX_DDL.SET_ATTRIBUTE('MY_TEXT_STORE', 'K_TABLE_CLAUSE','TABLESPACE ' || v_novo_tbs);
      CTX_DDL.SET_ATTRIBUTE('MY_TEXT_STORE', 'R_TABLE_CLAUSE','TABLESPACE ' || v_novo_tbs);
      CTX_DDL.SET_ATTRIBUTE('MY_TEXT_STORE', 'N_TABLE_CLAUSE','TABLESPACE ' || v_novo_tbs);
      CTX_DDL.SET_ATTRIBUTE('MY_TEXT_STORE', 'I_INDEX_CLAUSE','TABLESPACE ' || v_novo_tbs);
      ctx_ddl.set_attribute('MY_TEXT_STORE', 'P_TABLE_CLAUSE','TABLESPACE ' || v_novo_tbs);
END;
/

CREATE INDEX ADMSADP.&INDEX_NAME ON &SCHEMA_NAME.&TABLE_NAME(&COLUMN_NAME) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS('storage MY_TEXT_STORE');
/

BEGIN
  CTX_DDL.DROP_PREFERENCE(USER || '.MY_TEXT_STORE');
END;
/