UNDEFINE SCHEMA
UNDEFINE USER
SET SERVEROUTPUT ON
DECLARE
  V_SCHEMA VARCHAR2(200) := '&SCHEMA_ORIGEM';
  V_USER   VARCHAR2(200) := '&USER_DESTINO';

BEGIN   
       
  FOR I IN (  SELECT  OWNER, OBJECT_NAME, OBJECT_TYPE
              FROM    DBA_OBJECTS WHERE OWNER = V_SCHEMA
              AND     OBJECT_TYPE IN ('SEQUENCE','PROCEDURE','MATERIALIZED VIEW', 'FUNCTION', 'VIEW', 'TABLE', 'TYPE', 'PACKAGE')
            )  
  LOOP
      IF I.OBJECT_TYPE IN ('SEQUENCE', 'MATERIALIZED VIEW', 'VIEW') THEN
          DBMS_OUTPUT.PUT_LINE('GRANT SELECT  ON ' || V_SCHEMA || '.' || I.OBJECT_NAME || ' TO ' || V_USER || ';');
      ELSIF I.OBJECT_TYPE IN ('TABLE') THEN
          DBMS_OUTPUT.PUT_LINE('GRANT SELECT, INSERT, UPDATE, DELETE ON ' || V_SCHEMA || '.' || I.OBJECT_NAME || ' TO ' || V_USER || ';');
      ELSIF I.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION', 'PACKAGE', 'TYPE') THEN
          DBMS_OUTPUT.PUT_LINE('GRANT EXECUTE ON ' || V_SCHEMA || '.' || I.OBJECT_NAME || ' TO ' || V_USER || ';');      
      END IF;
  END LOOP;
END;