UNDEFINE SCHEMA
UNDEFINE USER
SET SERVEROUTPUT ON

DECLARE
  SCHEMA VARCHAR2(200);
  USER   VARCHAR2(200);

BEGIN
   
   :SCHEMA := '&SCHEMA';
   :USER   := '&USER';
   
   FOR I IN (SELECT TABLE_NAME FROM DBA_TABLES WHERE OWNER = :SCHEMA)
   LOOP
       DBMS_OUTPUT.PUT_LINE('GRANT SELECT, INSERT, UPDATE, DELETE ON ' || :SCHEMA || '.' || I.TABLE_NAME || ' TO ' || :USER || ';');
   END LOOP;
END;