
DBMS_METADATA.GET_DDL('USER','SCOTT')
DBMS_METADATA.GET_GRANTED_DDL('ROLE_GRANT','SCOTT')

SELECT DBMS_METADATA.GET_GRANTED_DDL('OBJECT_GRANT','SCOTT') from dual;
 SELECT DBMS_METADATA.GET_GRANTED_DDL('SYSTEM_GRANT','SCOTT') from dual;
 