-- remover privs auditados de todos os usuarios
BEGIN
    FOR LINHA IN (SELECT  'NOAUDIT ' || AUDIT_OPTION AS CMD
                  FROM    DBA_STMT_AUDIT_OPTS
                  WHERE   USER_NAME IS NULL)
    LOOP
        EXECUTE IMMEDIATE LINHA.CMD;
    END LOOP;
END;
/

-- modelo de auditoria padrao para ser habilitada nos BDs
AUDIT CONNECT WHENEVER NOT SUCCESSFUL;
audit session whenever not successful;
AUDIT SELECT TABLE, INSERT TABLE, DELETE TABLE, UPDATE TABLE, EXECUTE PROCEDURE BY ACCESS WHENEVER NOT SUCCESSFUL;
audit CREATE EXTERNAL JOB;
audit CREATE ANY JOB;
audit GRANT ANY OBJECT PRIVILEGE;
audit EXEMPT ACCESS POLICY;               
audit CREATE ANY LIBRARY;
audit GRANT ANY PRIVILEGE;
audit DROP ANY PROCEDURE;
audit ALTER ANY PROCEDURE;
audit CREATE ANY PROCEDURE;
audit ALTER DATABASE;
audit GRANT ANY ROLE;
audit CREATE PUBLIC DATABASE LINK;
audit DROP ANY TABLE;
audit ALTER ANY TABLE;
audit CREATE ANY TABLE;
audit DROP USER;
audit ALTER USER;
audit CREATE USER;
