select  S.SID, S.SERIAL#, S.USERNAME, S.STATUS, S.MACHINE, S.PROGRAM,
        O.OBJECT_NAME, L.* 
from    V$LOCKED_OBJECT L
JOIN    DBA_OBJECTS O
  ON    L.OBJECT_ID = O.OBJECT_ID
JOIN    V$SESSION S
  ON    S.SID = L.SESSION_ID
WHERE   OBJECT_NAME in ('&NOME_OBJETO');