--ATUALIZAR TODAS AS VIEWS MATERIALIZADAS DO SCHEMA

BEGIN
      FOR i in (SELECT MVIEW_NAME FROM DBA_MVIEWS WHERE OWNER = '&OWNER')
      LOOP
        DBMS_MVIEW.REFRESH('&SCHEMA..'||i.MVIEW_NAME,'C');
      END LOOP;
END;