SELECT      NVL(A.USERNAME,'(oracle)') AS USERNAME,
            a.module,
            A.PROGRAM,
            SUM(DECODE(A.SERVER,'DEDICATED',1,0)) AS TOTAL_DEDICATED,
            SUM(DECODE(A.SERVER,'DEDICATED',0,1)) AS TOTAL_SHARED,
            ROUND(SUM(DECODE(A.SERVER,'DEDICATED',B.VALUE,0))/1024/1024,2) AS MB_MEMORY_PGA,
            ROUND(SUM(DECODE(A.SERVER,'DEDICATED',0,B.VALUE))/1024/1024,2) AS MB_MEMORY_LARGEPOOL
            ,COUNT(NVL(A.USERNAME,'(oracle)')) AS QTD_SESSIONS
FROM        V$SESSION A
INNER JOIN  V$SESSTAT B
    ON      a.sid = b.sid
INNER JOIN  V$STATNAME C
    ON      B.STATISTIC# = C.STATISTIC#
WHERE       C.NAME = 'session pga memory' 
GROUP BY    NVL(A.USERNAME,'(oracle)'),
            A.MODULE,
            A.PROGRAM
ORDER BY    ROUND(SUM(B.VALUE)/1024/1024,2) DESC;